version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - echo "Starting Maven build"
      - mvn -B -DskipTests clean package

artifacts:
  files:
    - target/*.jar

