version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "Starting Maven build"
      - mvn clean package -DskipTests
      - echo "Build completed, artifact ready"
artifacts:
  files:
    - target/*.jar
